### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by UgoPoddine** [ThreeSixes/js8cli#5]
It would be useful to add some kind of :

js8cli "aprsemail"

function, in order to perform the short email transmission JS8CALL to APRS, with the syntax 👍 

@APRSIS CMD :EMAIL-2  :<email address> <email text> {<progressive number>}

This is useful in countries where the SMS service is not available.

Thank-you for your attention, good job in any case

73, IU1IPB
Ugo

**Comment by ThreeSixes** [comment]
That's a great suggestion. I'll add that soon.

**Comment by ThreeSixes** [comment]
Support for this feature has been added and merged.
